[package]
name = "mahjong-combinations"
version = "0.1.0"
authors = ["Aleksi Jokela <aleksi@suhina.solutions>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
enum-iterator = "*"
